### ISSUE TITLE
Multi-Paragraph Lists not rendered correctly

### ISSUE THREAD

**Issue by fthommen** [mprins/dokuwiki-plugin-yalist#4]
## Environment
- php version: 5.6.20
- dokuwiki version: 2015-08-10a "Detritus"
- plugin version: 2016-02-05
- list of any other plugins (apart from bundled plugins): acl     authchained    authpgsql  davcal     googlecal   info     permissioninfo  rss       styling  virtualgroup   yalist
  action.php  authldap       auth.php   dir    groupusers  move     popularity      safefnrecode  syntax.php   widearea
  admin.php   authldaplocal  authplain  edittable  index.html  note     remote.php      simplenavi    upgrade  wrap
  authad      authmysql      config     extension  indexmenu   nspages  revert          sqlite        usermanager 
## Problem

```
  * Unordered list item
  ** Unordered list item...
  .. ... in multiple paragraphs
```

Renders as
![yalist_wrong_rendering](https://cloud.githubusercontent.com/assets/279232/15857186/5187a486-2cba-11e6-925b-1a62d855a08a.png)

and results in the following HTML code:

```
<ul>
<li class="level1"><div class="li"> Unordered list item</div>
</li>
<li class="level1"><div class="li">* Unordered list item…</div>
</li>
</ul>

<p>
  .. … in multiple paragraphs
</p>
```

The same is valid for the other list types

**Comment by mprins** [comment]
I'm not sure you can mix list types, but I have never tried

**Comment by fthommen** [comment]
These are the examples from your own plugin page (https://www.dokuwiki.org/plugin:yalist) :-)

**Comment by fthommen** [comment]
I just retried and it seems that it now works.  I wonder if there were some invisible characters that I had initially copied.  I'll close the issue now.
