### ISSUE TITLE
list css

### ISSUE THREAD

**Issue by jlAlice** [mprins/dokuwiki-plugin-yalist#6]
Is it possible to remove selectors "div.dokuwiki .li" in CSS file in order it not to interfere the default list style?

**Comment by mprins** [comment]
I have no problem merging a PR with that change; have no idea of the impact, never checked the css of this plugin.

**Comment by jlAlice** [comment]
Thanx! I made a pull request.

**Comment by mprins** [comment]
I beat you to it, so I closed #8
